# Generated by Django 3.1.1 on 2020-09-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_auto_20200919_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tools',
            old_name='houner',
            new_name='owner',
        ),
    ]
