# Generated by Django 3.1.1 on 2020-09-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_auto_20200919_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='is_rented',
            field=models.CharField(default='true', max_length=5, null=True),
        ),
    ]
